### ISSUE TITLE
Fails the current check if any error found

### ISSUE THREAD

**Issue by ernestkamara** [alaegin/Detekt-Action#20]
Hi,
I set up this action as suggested. However, the checks pass with errors. Any idea, how I can fail the current check on error?

Workflow
```kotlin
  ...
  detekt:
    name: Running Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Clone Run detekt with reviewdog repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
      - name: Detekt
        uses: DominuS-RU/Detekt-Action@v1.15.0
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: detekt.yml
          reviewdog_reporter: github-pr-review
          detekt_excludes: '**/build/**,**/shared/db.dao/**,**.kts**,**/buildSrc/**,**/.idea/**'

```

<img width="1435" alt="Screenshot 2021-01-26 at 21 20 39" src="https://user-images.githubusercontent.com/502798/105900624-992ac580-601c-11eb-9586-84260469c64a.png">

Would be nice to add a `fail_on_error` input just as in https://github.com/ScaCap/action-ktlint#fail_on_error.

Thanks!

**Comment by alaegin** [comment]
Hello @ernestkamara!
Many apologies for such an indecently long wait.

I've added the feature you requested in #21.
Thank you for your request and for providing the link to ktlint documentation.

You can use this feature in [v1.15.0.1](https://github.com/alaegin/Detekt-Action/releases/tag/v1.15.0.1) or [v1.16.0-RC1](https://github.com/alaegin/Detekt-Action/releases/tag/v1.16.0-RC1) versions
