### ISSUE TITLE
InjectDispatcher rule is not working

### ISSUE THREAD

**Issue by ibtehaaj87** [alaegin/Detekt-Action#51]
I wrote the following code which is clearly non-compliant.

    suspend fun sample() {
        CoroutineScope(Dispatchers.IO).launch{

        }
        GlobalScope.launch(Dispatchers.IO){

        }
    }

But it doesn't show warning on this line that the dispatchers should only be injected. I have also set the rule to active in the config file. 

    coroutines:
      active: true
      GlobalCoroutineUsage:
        active: false
      InjectDispatcher:
        active: true
        dispatcherNames:
          - 'IO'
          - 'Default'
          - 'Unconfined'
      RedundantSuspendModifier:
        active: false
      SleepInsteadOfDelay:
        active: false
      SuspendFunWithFlowReturnType:
        active: false

**Comment by alaegin** [comment]
Hello!

This repository provides the wrapper around the original library. All issues about rules should be reported to the https://github.com/detekt/detekt repository.
