### ISSUE TITLE
Update reviewdog 0.17.4

### ISSUE THREAD

**Issue by franciscofranco** [alaegin/Detekt-Action#63]
Can you update reviewdog version? There's a bug in reviewdog where if your PR has more than 300 files changed it just craps out. Recent versions seem to fix it. Thanks

**Comment by alaegin** [comment]
Hello!

Please check v1.23.6.1 https://github.com/alaegin/Detekt-Action/releases/tag/v1.23.6.1

**Comment by franciscofranco** [comment]
Magic. Thanks.
